In [2]:
using LinearAlgebra, Statistics

In [2]:
a = [10, 20, 30]

3-element Vector{Int64}:
 10
 20
 30

In [3]:
a = [1.0, 2.0, 3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [8]:
typeof(randn(100))

Vector{Float64} (alias for Array{Float64, 1})

In [9]:
ndims(a)

1

In [10]:
size(a)

(3,)

In [12]:
[1, 2, 3] == [1; 2; 3] ## both column vectors

true

In [13]:
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [17]:
[1 2 3] * [1, 2, 3] ## some matrix algebra

1-element Vector{Int64}:
 14

In [18]:
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [20]:
zeros(2,2) ## The zeros command can make a matrix

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [22]:
fill(5.0, 2, 2) ## to make an array filled with a single value (5.0 in this case)

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

In [24]:
x = Array{Float64}(undef, 2, 2) ## you can create an empty array using the 'Array' constructor

2×2 Matrix{Float64}:
 6.36599e-314  0.0
 4.24399e-314  6.95293e-310

In [3]:
fill(0,2,2) ## Intuitively its a 2 by 2 matrix

2×2 Matrix{Int64}:
 0  0
 0  0

In [7]:
fill(false, 2, 2) ## can fill the matrix with boolean (false is 0)

2×2 Matrix{Bool}:
 0  0
 0  0

In [18]:
x = [1, 2, 3] 
y = x ## y = x simply creates a new named binding called y which refers to whatever x currently binds to.
y[2]

2

In [21]:
## To copy the data you need to be more explicit.
##
x = [1, 2, 3]
y = copy(x)
y[1]
x

3-element Vector{Int64}:
 1
 2
 3

In [24]:
x = [1, 2, 3]
y = similar(x)
@show x

x = [1, 2, 3]


3-element Vector{Int64}:
 1
 2
 3

In [25]:
x = [1, 2, 3]
y = similar(x, 4) ## make a vector of length 4

4-element Vector{Int64}:
             1
             3
 1749299514192
 1749299514256

In [26]:
x = [1, 2, 3]
y = similar(x, 2, 2)

2×2 Matrix{Int64}:
         285212672  1099511628033
 72339073326448640  1749244379144

In [27]:
a = [10, 20, 30, 40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [28]:
ndims(a)

1