In [1]:
using LinearAlgebra, Statistics

In [2]:
a = [10, 20, 30]

3-element Vector{Int64}:
 10
 20
 30

In [3]:
a = [1.0, 2.0, 3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [4]:
typeof(randn(100))

Vector{Float64} (alias for Array{Float64, 1})

In [5]:
ndims(a)

1

In [6]:
size(a)

(3,)

In [7]:
[1, 2, 3] == [1; 2; 3] ## both column vectors

true

In [8]:
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [9]:
[1 2 3] * [1, 2, 3] ## some matrix algebra

1-element Vector{Int64}:
 14

In [10]:
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [11]:
zeros(2,2) ## The zeros command can make a matrix

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [12]:
fill(5.0, 2, 2) ## to make an array filled with a single value (5.0 in this case)

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

In [13]:
x = Array{Float64}(undef, 2, 2) ## you can create an empty array using the 'Array' constructor

2×2 Matrix{Float64}:
 0.0       8.17001e-312
 1.0e-323  8.17001e-312

In [14]:
fill(0,2,2) ## Intuitively its a 2 by 2 matrix

2×2 Matrix{Int64}:
 0  0
 0  0

In [15]:
fill(false, 2, 2) ## can fill the matrix with boolean (false is 0)

2×2 Matrix{Bool}:
 0  0
 0  0

In [16]:
x = [1, 2, 3] 
y = x ## y = x simply creates a new named binding called y which refers to whatever x currently binds to.
y[2]

2

In [17]:
## To copy the data you need to be more explicit.
##
x = [1, 2, 3]
y = copy(x)
y[1]
x

3-element Vector{Int64}:
 1
 2
 3

In [18]:
x = [1, 2, 3]
y = similar(x)
@show x

x = [1, 2, 3]


3-element Vector{Int64}:
 1
 2
 3

In [19]:
x = [1, 2, 3]
y = similar(x, 4) ## make a vector of length 4

4-element Vector{Int64}:
 140726412153920
   1653616092016
   1653616092304
   1653616092592

In [20]:
x = [1, 2, 3]
y = similar(x, 2, 2)

2×2 Matrix{Int64}:
             31506  1099511628033
 72339073326448642  1653616082952

In [21]:
a = [10, 20, 30, 40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [22]:
ndims(a)

1

In [23]:
a = [10 20; 30 40]

2×2 Matrix{Int64}:
 10  20
 30  40

In [24]:
a = [10; 20; 30; 40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [25]:
ndims(a)

1

In [26]:
a = [10 20; 30 40]'

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 10  30
 20  40

In [27]:
ndims(a)

2

In [28]:
typeof(a)

Adjoint{Int64, Matrix{Int64}}

In [29]:
[1; 2]

2-element Vector{Int64}:
 1
 2

In [30]:
[1; 2;;]

2×1 Matrix{Int64}:
 1
 2

In [31]:
[1; 2;;;]

2×1×1 Array{Int64, 3}:
[:, :, 1] =
 1
 2

In [32]:
[1;;]

1×1 Matrix{Int64}:
 1

In [33]:
[1 2; 3 4;;;]

2×2×1 Array{Int64, 3}:
[:, :, 1] =
 1  2
 3  4

In [34]:
a = [10 20 30 40]
a[end - 1]

30

In [35]:
a = rand(2,2)

2×2 Matrix{Float64}:
 0.389215  0.800226
 0.418548  0.992655

In [36]:
a[1,1]

0.3892154026105128

In [37]:
a[1,:]

2-element Vector{Float64}:
 0.3892154026105128
 0.8002259870798054

In [38]:
a = rand(2,2)
b = [true false; false true]
a[b]

2-element Vector{Float64}:
 0.059150450885408934
 0.54807161921638

In [39]:
a = zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [40]:
a[2:end] .= 42

3-element view(::Vector{Float64}, 2:4) with eltype Float64:
 42.0
 42.0
 42.0

In [41]:
a

4-element Vector{Float64}:
  0.0
 42.0
 42.0
 42.0

In [42]:
a = [1 2; 3 4]
b = a[:, 2]
@show b
a[:, 2] = [4, 5]
a

b = [2, 4]

2×2 Matrix{Int64}:
 1  4
 3  5

In [43]:
a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [44]:
b = a[:, 1]

2-element Vector{Int64}:
 1
 3

In [45]:
@views b = a[:, 2]

2-element view(::Matrix{Int64}, :, 2) with eltype Int64:
 2
 4

In [46]:
view(a, :, 2) == b

true

In [47]:
a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [48]:
b_slice = a[:, 2]

2-element Vector{Int64}:
 2
 4

In [49]:
typeof(b_slice)

Vector{Int64} (alias for Array{Int64, 1})

In [50]:
typeof(a)

Matrix{Int64} (alias for Array{Int64, 2})

In [51]:
@views b =  a[:, 2]

2-element view(::Matrix{Int64}, :, 2) with eltype Int64:
 2
 4

In [52]:
typeof(b)

SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}

In [53]:
a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [54]:
b = a'

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [55]:
typeof(b)

Adjoint{Int64, Matrix{Int64}}

In [56]:
a = [1 2; 3 4]
b = a'
c = Matrix(b)
d = collect(b)
c == d

true

In [57]:
d = [1.0 2.0]

a = Diagonal(b)

2×2 Diagonal{Int64, Vector{Int64}}:
 1  ⋅
 ⋅  4

In [58]:
@show 2a

2a = [2 0; 0 8]


2×2 Diagonal{Int64, Vector{Int64}}:
 2  ⋅
 ⋅  8

In [59]:
b = rand(2, 2)

2×2 Matrix{Float64}:
 0.173788  0.352239
 0.98048   0.581379

In [60]:
@show b * a

b * a = [0.17378778496626068 1.4089568092907139; 0.9804800994168624 2.3255149875034604]


2×2 Matrix{Float64}:
 0.173788  1.40896
 0.98048   2.32551

In [61]:
b = [1.0 2.0; 3.0 4.0]
b - Diagonal([1.0, 1.0])

2×2 Matrix{Float64}:
 0.0  2.0
 3.0  3.0

In [62]:
b = [1.0 2.0; 3.0 4.0]
b - I ## I is an identity matrix

2×2 Matrix{Float64}:
 0.0  2.0
 3.0  3.0

In [63]:
typeof(I)

UniformScaling{Bool}

In [64]:
x = [1, 2, 3]
y = x ## name y is bound to whatever x is bound to 
z = [2, 3, 4]
y = z ## only changes the binding not the value
@show (x, y, z);

(x, y, z) = ([1, 2, 3], [2, 3, 4], [2, 3, 4])


In [65]:
x = [1, 2, 3]
y = x
z = [2, 3, 4]
y .= z
@show (x, y, z)

(x, y, z) = ([2, 3, 4], [2, 3, 4], [2, 3, 4])


([2, 3, 4], [2, 3, 4], [2, 3, 4])

In [66]:
function f(x)
    return [1 2; 3 4] * x ## matrix * column vector
end

val = [1, 2]
f(val)

2-element Vector{Int64}:
  5
 11

In [67]:
function f(x)
    return [1 2; 3 4] * x
end

val = [1, 2]
y = similar(val)

function f!(out, x)
    out .= [1 2; 3 4] * x
end

f!(y, val)
y

2-element Vector{Int64}:
  5
 11

In [68]:
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [69]:
function f(x)
    return [1 2; 3 4] * x
end

val = [1, 2]
y = similar(val)

function f!(out, x)
    out .= [1 2; 3 4] * x
end

f!(y, val)

2-element Vector{Int64}:
  5
 11

In [70]:
y = [1 2]

1×2 Matrix{Int64}:
 1  2

In [71]:
y .-= 2

x = 5

x = x - 2

3

In [72]:
x = 2

function f(x)
    x = 3
end

f(x)
@show x

x = 2


2

In [73]:
using StaticArrays

xdynamic = [1, 2]
xstatic = @SVector [1, 2] # turns it to a highly optimised static vector

f(x) = 2x

# in place version
function g(x)
    x .= 2x
    return "Success!"
end

@show xdynamic
@show g(xdynamic)
@show xdynamic;

xdynamic = [1, 2]
g(xdynamic) = "Success!"
xdynamic = [2, 4]


In [74]:
## Operations and arrays

a = [-1, 0, 1]
@show a
@show length(a)
@show sum(a)
@show mean(a)
@show std(a)
@show var(a)
@show minimum(a)
@show maximum(a)
@show extrema(a)

a = [-1, 0, 1]
length(a) = 3
sum(a) = 0
mean(a) = 0.0
std(a) = 1.0
var(a) = 1.0
minimum(a) = -1
maximum(a) = 1
extrema(a) = (-1, 1)


(-1, 1)

In [75]:
## To sort an array
b = sort(a, rev = true)
@show b

b = sort!(a, rev = true)

b = [1, 0, -1]


3-element Vector{Int64}:
  1
  0
 -1

In [76]:
## test if a and b are equal after you reverse it
a == b

true

In [77]:
## test if a and b are identical (i.e. share the same memory)
a === b

true

In [78]:
## Matrix algebra
a = ones(1, 2)
b = ones(2, 2)
@show a
@show b

c = a * b
d = b * a'
@show c
d

a = [1.0 1.0]
b = [1.0 1.0; 1.0 1.0]
c = [2.0 2.0]


2×1 Matrix{Float64}:
 2.0
 2.0

In [79]:
## Solve the linear system AX = B for X use A/B
A = [1 2; 2 3]
B = ones(2,2)

A\B

inv(A) * B

2×2 Matrix{Float64}:
 -1.0  -1.0
  1.0   1.0

In [80]:
ones(2)' * ones(2)

2.0

In [81]:
@show dot(ones(2)', ones(2))
@show ones(2) ⋅ ones(2)

dot((ones(2))', ones(2)) = 2.0
ones(2) ⋅ ones(2) = 2.0


2.0

In [82]:
## Elementwise operations
## if you want to multiply every element in of matrix A with its corresponding element in B then you can use ".*"
A = ones(2,2)
B = ones(2, 2)
A.*B

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [83]:
## same with squaring a result
A.^2

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [84]:
## there are operations that are mathematically valid without broadcasting, so you don't need "."
@show ones(2,2) + ones(2,2)
@show ones(2,2) - ones(2,2);

A = [1 1; 2 2]
3A

ones(2, 2) + ones(2, 2) = [2.0 2.0; 2.0 2.0]
ones(2, 2) - ones(2, 2) = [0.0 0.0; 0.0 0.0]


2×2 Matrix{Int64}:
 3  3
 6  6

In [85]:
## However, scalar addition requires a broadcast
A = [1 2; 3 4]
3 .+ A

2×2 Matrix{Int64}:
 4  5
 6  7

In [86]:
## Elementwise comparisons
a = [20, 30, 40]
b = [-100, 0, 100]
b .> a
b.==a
b .> 1


3-element BitVector:
 0
 0
 1

In [87]:
## Conditional extraction
a = rand(4)

4-element Vector{Float64}:
 0.030046704238010258
 0.060689139557860705
 0.5062989478580181
 0.4671284785942186

In [88]:
@show a[a .> 0]

a[a .> 0] = [0.030046704238010258, 0.060689139557860705, 0.5062989478580181, 0.4671284785942186]


4-element Vector{Float64}:
 0.030046704238010258
 0.060689139557860705
 0.5062989478580181
 0.4671284785942186

In [89]:
## Changing dimensions
a = [1,2,3,4]
a = a*10
b = reshape(a, 2,2)

2×2 Matrix{Int64}:
 10  30
 20  40

In [90]:
b[1, 2]

30

In [91]:
## Drop an array along one dimension
a = [1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [92]:
dropdims(a, dims = 1)

4-element Vector{Int64}:
 1
 2
 3
 4

In [93]:
## Broadcastig functions
log(1.0)
log.(1:4)
[log(x) for x in 1:4]

4-element Vector{Float64}:
 0.0
 0.6931471805599453
 1.0986122886681098
 1.3862943611198906

In [94]:
## Linear algebra
A = [1 2; 4 3]

2×2 Matrix{Int64}:
 1  2
 4  3

In [95]:
det(A)

-5.0

In [96]:
tr(A) ## trace of matix which takes the sum of the diagonal values of the matrix

4

In [97]:
eigvals(A)

2-element Vector{Float64}:
 -1.0
  5.0

In [98]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [99]:
B = ones(2,2)

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [100]:
a = [1,3]

2-element Vector{Int64}:
 1
 3

In [101]:
b = [3, 4]

2-element Vector{Int64}:
 3
 4

In [102]:
c = [1,2,3,4,5,6,7,8,9,10]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [103]:
c'*c

385

In [104]:
A = [1 2 3;4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [105]:
A'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [106]:
a = 1:10

1:10

In [107]:
@show Vector(a)

Vector(a) = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [108]:
b = Diagonal(a)

10×10 Diagonal{Int64, UnitRange{Int64}}:
 1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  2  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  3  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  4  ⋅  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  5  ⋅  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  6  ⋅  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  7  ⋅  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  8  ⋅   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  9   ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  10

In [109]:
b*a

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [110]:
b = Diagonal([1.0, 2.0, 3.0])

3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   2.0   ⋅ 
  ⋅    ⋅   3.0

In [111]:
a = 10:12

10:12

In [112]:
b * a

3-element Vector{Float64}:
 10.0
 22.0
 36.0

In [113]:
b * a - [1.0, 2.0, 3.0]

3-element Vector{Float64}:
  9.0
 20.0
 33.0

In [114]:
a = 0.0:0.1:1.0

0.0:0.1:1.0

In [115]:
a .+ 0.01

0.01:0.1:1.01

In [116]:
maxval = 1.0
minval = 0.0
stepsize = 0.15
a = minval:stepsize:maxval

0.0:0.15:0.9

In [117]:
maximum(a) == maxval

false

In [118]:
t = (1.0, "apple")

(1.0, "apple")

In [119]:
t[1]

1.0

In [120]:
t[2]

"apple"

In [121]:
a, b = t

(1.0, "apple")

In [122]:
println("a = $a and b = $b")

a = 1.0 and b = apple


In [123]:
t = (; val1 = 1.0, val2 = "test")

(val1 = 1.0, val2 = "test")

In [124]:
println("a = $(t.val1) and b= $(t.val2)")

a = 1.0 and b= test


In [125]:
(; val1, val2) = t
println("a = $val1 and b = $val2")

a = 1.0 and b = test


In [126]:
t2 = (;val3 = 4, val4 = "test!!")

(val3 = 4, val4 = "test!!")

In [127]:
t3 = merge(t, t2)

(val1 = 1.0, val2 = "test", val3 = 4, val4 = "test!!")

In [128]:
function f(parameters)
    alpha, beta = parameters.alpha, parameters.beta
    return alpha + beta
end

parameters = (; alpha = 0.1, beta = 2.0)
f(parameters)

2.1

In [129]:
function f(parameters)
    (; alpha, beta) = parameters
    return alpha + beta
end
parameters = (; alpha = 1.5, beta = 2.2)

f(parameters)

3.7

In [130]:
function param_gen(; alpha = 1.0, beta = 0.2)
    return alpha + beta
end

@show param_gen()
@show param_gen(alpha = 0.2)

param_gen() = 1.2
param_gen(alpha = 0.2) = 0.4


0.4

In [131]:
## Nothing
typeof(nothing)

Nothing

In [132]:
## Missing
typeof(missing)

Missing

In [133]:
function f(y)
    x = nothing
    if y > 0.0
        # calculations to set 'x'
        x = y
    end

    # later can check 'x'
    if isnothing(x)
        println("x was not set")
    else
        println("x = $x")
    end
    x
end

@show f(1.0)
@show f(-1.0)

x = 1.0
f(1.0) = 1.0
x was not set
f(-1.0) = nothing


In [134]:
function f(x)
    if x > 0.0
        return sqrt(x)
    else
        return nothing
    end
end

x1 = 1.0
x2 = -1.0

y1 = f(x1)
y2 = f(x2)

if isnothing(y1)
    println("function f($x2) is successful")
else
    println("function f($x2) failed")
end

function f(-1.0) failed


In [135]:
function f(x)
    x > 0.0 ? sqrt(x) : nothing

end

f(-1.0)

In [136]:
x = [1.0, nothing]

2-element Vector{Union{Nothing, Float64}}:
 1.0
  nothing

In [137]:
x = [0.1, -1.0, 2.0, -2.0]
y = f.(x)

4-element Vector{Union{Nothing, Float64}}:
 0.31622776601683794
  nothing
 1.4142135623730951
  nothing

In [138]:
function f(x)
    @assert x > 0.0
    sqrt(x)
end

f(1.0)

1.0

In [141]:
function f(x; y = nothing)
    if isnothing(y)
        println("No y is given with $x")
    else
        println("y = $y with $x")
    end
end

f(1.0)
    

No y is given with 1.0


In [144]:
f(1.0, y = 2.0)

y = 2.0 with 1.0


In [145]:
function f(x)
    if x > 0.0
        return x
    else
        return NaN
    end
end

f(0.1)

0.1

In [146]:
f(-0.1)

NaN

In [148]:
typeof(f(0.2))

Float64

In [150]:
f(-0.1)==NaN 

false

In [151]:
try
    sqrt(-1)
catch err
    err
end

DomainError(-1.0, "sqrt was called with a negative real argument but will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).")

In [152]:
sqrt(-1)

LoadError: DomainError with -1.0:
sqrt was called with a negative real argument but will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

In [153]:
try 
    convert(Int64, 3.14)
catch err
    err
end


InexactError(:Int64, Int64, 3.14)

In [154]:
function f(x)
    try 
        sqrt(x)
    catch err
        sqrt(complex(x,0))
    end
end

f(1.0)

1.0

In [155]:
f(-1)

0.0 + 1.0im

In [156]:
x = [1.0, missing, 2.0, missing, missing, 5.0]

6-element Vector{Union{Missing, Float64}}:
 1.0
  missing
 2.0
  missing
  missing
 5.0

In [157]:
f(x) = x^2

f (generic function with 1 method)

In [158]:
f(x)

LoadError: MethodError: no method matching ^(::Vector{Union{Missing, Float64}}, ::Int64)

Closest candidates are:
  ^(::Irrational{:ℯ}, ::Integer)
   @ Base mathconstants.jl:119
  ^(::BigFloat, ::Integer)
   @ Base mpfr.jl:670
  ^(::Float64, ::Integer)
   @ Base math.jl:1246
  ...


In [159]:
@show missing + 1

missing + 1 = missing


missing

In [160]:
@show missing*2

missing * 2 = missing


missing

In [161]:
@show f(missing)

f(missing) = missing


missing

In [162]:
@show f(1)

f(1) = 1


1

In [163]:
@show mean(x)

mean(x) = missing


missing

In [164]:
x = missing

missing

In [165]:
x == missing

missing

In [166]:
x === missing

true

In [167]:
ismissing(missing)

true

In [169]:
x = [1.0, missing, 3.0, 4.0, missing]

5-element Vector{Union{Missing, Float64}}:
 1.0
  missing
 3.0
 4.0
  missing

In [171]:
coalesce.(x, 0.0)

5-element Vector{Float64}:
 1.0
 0.0
 3.0
 4.0
 0.0