In [1]:
using LinearAlgebra, Statistics

In [2]:
a = [10, 20, 30]

3-element Vector{Int64}:
 10
 20
 30

In [3]:
a = [1.0, 2.0, 3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [8]:
typeof(randn(100))

Vector{Float64} (alias for Array{Float64, 1})

In [9]:
ndims(a)

1

In [10]:
size(a)

(3,)

In [12]:
[1, 2, 3] == [1; 2; 3] ## both column vectors

true

In [13]:
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [17]:
[1 2 3] * [1, 2, 3] ## some matrix algebra

1-element Vector{Int64}:
 14

In [18]:
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [20]:
zeros(2,2) ## The zeros command can make a matrix

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [22]:
fill(5.0, 2, 2) ## to make an array filled with a single value (5.0 in this case)

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

In [24]:
x = Array{Float64}(undef, 2, 2) ## you can create an empty array using the 'Array' constructor

2×2 Matrix{Float64}:
 6.36599e-314  0.0
 4.24399e-314  6.95293e-310