In [1]:
using LinearAlgebra, Statistics

In [2]:
a = [10, 20, 30]

3-element Vector{Int64}:
 10
 20
 30

In [3]:
a = [1.0, 2.0, 3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [4]:
typeof(randn(100))

Vector{Float64} (alias for Array{Float64, 1})

In [5]:
ndims(a)

1

In [6]:
size(a)

(3,)

In [7]:
[1, 2, 3] == [1; 2; 3] ## both column vectors

true

In [8]:
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [9]:
[1 2 3] * [1, 2, 3] ## some matrix algebra

1-element Vector{Int64}:
 14

In [10]:
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [11]:
zeros(2,2) ## The zeros command can make a matrix

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [12]:
fill(5.0, 2, 2) ## to make an array filled with a single value (5.0 in this case)

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

In [13]:
x = Array{Float64}(undef, 2, 2) ## you can create an empty array using the 'Array' constructor

2×2 Matrix{Float64}:
 2.0237e-320   1.26337e-311
 1.26337e-311  1.26337e-311

In [14]:
fill(0,2,2) ## Intuitively its a 2 by 2 matrix

2×2 Matrix{Int64}:
 0  0
 0  0

In [15]:
fill(false, 2, 2) ## can fill the matrix with boolean (false is 0)

2×2 Matrix{Bool}:
 0  0
 0  0

In [16]:
x = [1, 2, 3] 
y = x ## y = x simply creates a new named binding called y which refers to whatever x currently binds to.
y[2]

2

In [17]:
## To copy the data you need to be more explicit.
##
x = [1, 2, 3]
y = copy(x)
y[1]
x

3-element Vector{Int64}:
 1
 2
 3

In [18]:
x = [1, 2, 3]
y = similar(x)
@show x

x = [1, 2, 3]


3-element Vector{Int64}:
 1
 2
 3

In [19]:
x = [1, 2, 3]
y = similar(x, 4) ## make a vector of length 4

4-element Vector{Int64}:
               0
 140735595860336
   2556091611216
               2

In [20]:
x = [1, 2, 3]
y = similar(x, 2, 2)

2×2 Matrix{Int64}:
               0  2556091539040
 140735595860336              2

In [21]:
a = [10, 20, 30, 40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [22]:
ndims(a)

1

In [23]:
a = [10 20; 30 40]

2×2 Matrix{Int64}:
 10  20
 30  40

In [24]:
a = [10; 20; 30; 40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [25]:
ndims(a)

1

In [26]:
a = [10 20; 30 40]'

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 10  30
 20  40

In [27]:
ndims(a)

2

In [28]:
typeof(a)

Adjoint{Int64, Matrix{Int64}}

In [29]:
[1; 2]

2-element Vector{Int64}:
 1
 2

In [30]:
[1; 2;;]

2×1 Matrix{Int64}:
 1
 2

In [31]:
[1; 2;;;]

2×1×1 Array{Int64, 3}:
[:, :, 1] =
 1
 2

In [32]:
[1;;]

1×1 Matrix{Int64}:
 1

In [33]:
[1 2; 3 4;;;]

2×2×1 Array{Int64, 3}:
[:, :, 1] =
 1  2
 3  4

In [34]:
a = [10 20 30 40]
a[end - 1]

30

In [35]:
a = rand(2,2)

2×2 Matrix{Float64}:
 0.707235  0.759744
 0.928741  0.712445

In [36]:
a[1,1]

0.7072351304553585

In [37]:
a[1,:]

2-element Vector{Float64}:
 0.7072351304553585
 0.7597435305687023

In [38]:
a = rand(2,2)
b = [true false; false true]
a[b]

2-element Vector{Float64}:
 0.3253896250398701
 0.34583246113573796

In [39]:
a = zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [40]:
a[2:end] .= 42

3-element view(::Vector{Float64}, 2:4) with eltype Float64:
 42.0
 42.0
 42.0

In [41]:
a

4-element Vector{Float64}:
  0.0
 42.0
 42.0
 42.0

In [42]:
a = [1 2; 3 4]
b = a[:, 2]
@show b
a[:, 2] = [4, 5]
a

b = [2, 4]


2×2 Matrix{Int64}:
 1  4
 3  5

In [43]:
a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [44]:
b = a[:, 1]

2-element Vector{Int64}:
 1
 3

In [45]:
@views b = a[:, 2]

2-element view(::Matrix{Int64}, :, 2) with eltype Int64:
 2
 4

In [46]:
view(a, :, 2) == b

true

In [47]:
a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [48]:
b_slice = a[:, 2]

2-element Vector{Int64}:
 2
 4

In [49]:
typeof(b_slice)

Vector{Int64} (alias for Array{Int64, 1})

In [50]:
typeof(a)

Matrix{Int64} (alias for Array{Int64, 2})

In [51]:
@views b =  a[:, 2]

2-element view(::Matrix{Int64}, :, 2) with eltype Int64:
 2
 4

In [52]:
typeof(b)

SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}

In [53]:
a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [54]:
b = a'

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [55]:
typeof(b)

Adjoint{Int64, Matrix{Int64}}

In [56]:
a = [1 2; 3 4]
b = a'
c = Matrix(b)
d = collect(b)
c == d

true

In [57]:
d = [1.0 2.0]

a = Diagonal(b)

2×2 Diagonal{Int64, Vector{Int64}}:
 1  ⋅
 ⋅  4

In [58]:
@show 2a

2a = [2 0; 0 8]


2×2 Diagonal{Int64, Vector{Int64}}:
 2  ⋅
 ⋅  8

In [59]:
b = rand(2, 2)

2×2 Matrix{Float64}:
 0.890131  0.707554
 0.907621  0.415128

In [60]:
@show b * a

b * a = [0.8901307295124098 2.8302174089360257; 0.9076210905312575 1.6605125514718986]


2×2 Matrix{Float64}:
 0.890131  2.83022
 0.907621  1.66051

In [61]:
b = [1.0 2.0; 3.0 4.0]
b - Diagonal([1.0, 1.0])

2×2 Matrix{Float64}:
 0.0  2.0
 3.0  3.0

In [62]:
b = [1.0 2.0; 3.0 4.0]
b - I ## I is an identity matrix

2×2 Matrix{Float64}:
 0.0  2.0
 3.0  3.0

In [63]:
typeof(I)

UniformScaling{Bool}

In [64]:
x = [1, 2, 3]
y = x ## name y is bound to whatever x is bound to 
z = [2, 3, 4]
y = z ## only changes the binding not the value
@show (x, y, z);

(x, y, z) = ([1, 2, 3], [2, 3, 4], [2, 3, 4])


In [65]:
x = [1, 2, 3]
y = x
z = [2, 3, 4]
y .= z
@show (x, y, z)

(x, y, z) = ([2, 3, 4], [2, 3, 4], [2, 3, 4])


([2, 3, 4], [2, 3, 4], [2, 3, 4])

In [66]:
function f(x)
    return [1 2; 3 4] * x ## matrix * column vector
end

val = [1, 2]
f(val)

2-element Vector{Int64}:
  5
 11

In [67]:
function f(x)
    return [1 2; 3 4] * x
end

val = [1, 2]
y = similar(val)

function f!(out, x)
    out .= [1 2; 3 4] * x
end

f!(y, val)
y

2-element Vector{Int64}:
  5
 11

In [68]:
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [69]:
function f(x)
    return [1 2; 3 4] * x
end

val = [1, 2]
y = similar(val)

function f!(out, x)
    out .= [1 2; 3 4] * x
end

f!(y, val)

2-element Vector{Int64}:
  5
 11

In [70]:
y = [1 2]

1×2 Matrix{Int64}:
 1  2

In [71]:
y .-= 2

x = 5

x = x - 2

3

In [72]:
x = 2

function f(x)
    x = 3
end

f(x)
@show x

x = 2


2

In [73]:
using StaticArrays

xdynamic = [1, 2]
xstatic = @SVector [1, 2] # turns it to a highly optimised static vector

f(x) = 2x

# in place version
function g(x)
    x .= 2x
    return "Success!"
end

@show xdynamic
@show g(xdynamic)
@show xdynamic;

xdynamic = [1, 2]
g(xdynamic) = "Success!"
xdynamic = [2, 4]


In [86]:
## Operations and arrays

a = [-1, 0, 1]
@show a
@show length(a)
@show sum(a)
@show mean(a)
@show std(a)
@show var(a)
@show minimum(a)
@show maximum(a)
@show extrema(a)

a = [-1, 0, 1]
length(a) = 3
sum(a) = 0
mean(a) = 0.0
std(a) = 1.0
var(a) = 1.0
minimum(a) = -1
maximum(a) = 1
extrema(a) = (-1, 1)


(-1, 1)

In [90]:
## To sort an array
b = sort(a, rev = true)
@show b

b = sort!(a, rev = true)

b = [1, 0, -1]


3-element Vector{Int64}:
  1
  0
 -1

In [92]:
## test if a and b are equal after you reverse it
a == b

true

In [93]:
## test if a and b are identical (i.e. share the same memory)
a === b

true

In [100]:
## Matrix algebra
a = ones(1, 2)
b = ones(2, 2)
@show a
@show b

c = a * b
d = b * a'
@show c
d

a = [1.0 1.0]
b = [1.0 1.0; 1.0 1.0]
c = [2.0 2.0]


2×1 Matrix{Float64}:
 2.0
 2.0

In [104]:
## Solve the linear system AX = B for X use A/B
A = [1 2; 2 3]
B = ones(2,2)

A\B

inv(A) * B

2×2 Matrix{Float64}:
 -1.0  -1.0
  1.0   1.0

In [106]:
ones(2)' * ones(2)

2.0

In [108]:
@show dot(ones(2)', ones(2))
@show ones(2) ⋅ ones(2)

dot((ones(2))', ones(2)) = 2.0
ones(2) ⋅ ones(2) = 2.0


2.0

In [111]:
## Elementwise operations
## if you want to multiply every element in of matrix A with its corresponding element in B then you can use ".*"
A = ones(2,2)
B = ones(2, 2)
A.*B

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [113]:
## same with squaring a result
A.^2

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [118]:
## there are operations that are mathematically valid without broadcasting, so you don't need "."
@show ones(2,2) + ones(2,2)
@show ones(2,2) - ones(2,2);

A = [1 1; 2 2]
3A

ones(2, 2) + ones(2, 2) = [2.0 2.0; 2.0 2.0]
ones(2, 2) - ones(2, 2) = [0.0 0.0; 0.0 0.0]


2×2 Matrix{Int64}:
 3  3
 6  6

In [120]:
## However, scalar addition requires a broadcast
A = [1 2; 3 4]
3 .+ A

2×2 Matrix{Int64}:
 4  5
 6  7

In [125]:
## Elementwise comparisons
a = [20, 30, 40]
b = [-100, 0, 100]
b .> a
b.==a
b .> 1


3-element BitVector:
 0
 0
 1

In [126]:
## Conditional extraction
a = rand(4)

4-element Vector{Float64}:
 0.3843755408460967
 0.40913107099992196
 0.8086479658109943
 0.8973714817174817

In [130]:
@show a[a .> 0]

a[a .> 0] = [0.3843755408460967, 0.40913107099992196, 0.8086479658109943, 0.8973714817174817]


4-element Vector{Float64}:
 0.3843755408460967
 0.40913107099992196
 0.8086479658109943
 0.8973714817174817

In [132]:
## Changing dimensions
a = [1,2,3,4]
a = a*10
b = reshape(a, 2,2)

2×2 Matrix{Int64}:
 10  30
 20  40

In [135]:
b[1, 2]

30

In [136]:
## Drop an array along one dimension
a = [1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [139]:
dropdims(a, dims = 1)

4-element Vector{Int64}:
 1
 2
 3
 4

In [147]:
## Broadcastig functions
log(1.0)
log.(1:4)
[log(x) for x in 1:4]

4-element Vector{Float64}:
 0.0
 0.6931471805599453
 1.0986122886681098
 1.3862943611198906

In [162]:
## Linear algebra
A = [1 2; 4 3]

2×2 Matrix{Int64}:
 1  2
 4  3

In [163]:
det(A)

-5.0

In [164]:
tr(A) ## trace of matix which takes the sum of the diagonal values of the matrix

4

In [165]:
eigvals(A)

2-element Vector{Float64}:
 -1.0
  5.0

In [166]:
rank(A)

2