In [1]:
using LinearAlgebra, Statistics

In [2]:
a = [10, 20, 30]

3-element Vector{Int64}:
 10
 20
 30

In [3]:
a = [1.0, 2.0, 3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [4]:
typeof(randn(100))

Vector{Float64} (alias for Array{Float64, 1})

In [5]:
ndims(a)

1

In [6]:
size(a)

(3,)

In [7]:
[1, 2, 3] == [1; 2; 3] ## both column vectors

true

In [8]:
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [9]:
[1 2 3] * [1, 2, 3] ## some matrix algebra

1-element Vector{Int64}:
 14

In [10]:
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [11]:
zeros(2,2) ## The zeros command can make a matrix

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [12]:
fill(5.0, 2, 2) ## to make an array filled with a single value (5.0 in this case)

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

In [13]:
x = Array{Float64}(undef, 2, 2) ## you can create an empty array using the 'Array' constructor

2×2 Matrix{Float64}:
 2.0237e-320   1.54866e-311
 1.54866e-311  1.54866e-311

In [14]:
fill(0,2,2) ## Intuitively its a 2 by 2 matrix

2×2 Matrix{Int64}:
 0  0
 0  0

In [15]:
fill(false, 2, 2) ## can fill the matrix with boolean (false is 0)

2×2 Matrix{Bool}:
 0  0
 0  0

In [16]:
x = [1, 2, 3] 
y = x ## y = x simply creates a new named binding called y which refers to whatever x currently binds to.
y[2]

2

In [17]:
## To copy the data you need to be more explicit.
##
x = [1, 2, 3]
y = copy(x)
y[1]
x

3-element Vector{Int64}:
 1
 2
 3

In [18]:
x = [1, 2, 3]
y = similar(x)
@show x

x = [1, 2, 3]


3-element Vector{Int64}:
 1
 2
 3

In [19]:
x = [1, 2, 3]
y = similar(x, 4) ## make a vector of length 4

4-element Vector{Int64}:
               0
 140729227335456
   3133529907184
               2

In [20]:
x = [1, 2, 3]
y = similar(x, 2, 2)

2×2 Matrix{Int64}:
               0  3133529907040
 140729227335456              2

In [21]:
a = [10, 20, 30, 40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [22]:
ndims(a)

1

In [23]:
a = [10 20; 30 40]

2×2 Matrix{Int64}:
 10  20
 30  40

In [24]:
a = [10; 20; 30; 40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [25]:
ndims(a)

1

In [26]:
a = [10 20; 30 40]'

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 10  30
 20  40

In [27]:
ndims(a)

2

In [28]:
typeof(a)

Adjoint{Int64, Matrix{Int64}}

In [29]:
[1; 2]

2-element Vector{Int64}:
 1
 2

In [30]:
[1; 2;;]

2×1 Matrix{Int64}:
 1
 2

In [31]:
[1; 2;;;]

2×1×1 Array{Int64, 3}:
[:, :, 1] =
 1
 2

In [32]:
[1;;]

1×1 Matrix{Int64}:
 1

In [33]:
[1 2; 3 4;;;]

2×2×1 Array{Int64, 3}:
[:, :, 1] =
 1  2
 3  4

In [34]:
a = [10 20 30 40]
a[end - 1]

30

In [35]:
a = rand(2,2)

2×2 Matrix{Float64}:
 0.484027  0.215001
 0.521383  0.108257

In [36]:
a[1,1]

0.4840270452735723

In [37]:
a[1,:]

2-element Vector{Float64}:
 0.4840270452735723
 0.21500070194382548

In [38]:
a = rand(2,2)
b = [true false; false true]
a[b]

2-element Vector{Float64}:
 0.13201183732587052
 0.37303112782359715

In [39]:
a = zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [40]:
a[2:end] .= 42

3-element view(::Vector{Float64}, 2:4) with eltype Float64:
 42.0
 42.0
 42.0

In [41]:
a

4-element Vector{Float64}:
  0.0
 42.0
 42.0
 42.0

In [42]:
a = [1 2; 3 4]
b = a[:, 2]
@show b
a[:, 2] = [4, 5]
a

b = [2, 4]


2×2 Matrix{Int64}:
 1  4
 3  5

In [43]:
a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [44]:
b = a[:, 1]

2-element Vector{Int64}:
 1
 3

In [45]:
@views b = a[:, 2]

2-element view(::Matrix{Int64}, :, 2) with eltype Int64:
 2
 4

In [46]:
view(a, :, 2) == b

true

In [47]:
a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [48]:
b_slice = a[:, 2]

2-element Vector{Int64}:
 2
 4

In [49]:
typeof(b_slice)

Vector{Int64} (alias for Array{Int64, 1})

In [50]:
typeof(a)

Matrix{Int64} (alias for Array{Int64, 2})

In [51]:
@views b =  a[:, 2]

2-element view(::Matrix{Int64}, :, 2) with eltype Int64:
 2
 4

In [52]:
typeof(b)

SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}

In [53]:
a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [54]:
b = a'

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [55]:
typeof(b)

Adjoint{Int64, Matrix{Int64}}

In [56]:
a = [1 2; 3 4]
b = a'
c = Matrix(b)
d = collect(b)
c == d

true

In [57]:
d = [1.0 2.0]

a = Diagonal(b)

2×2 Diagonal{Int64, Vector{Int64}}:
 1  ⋅
 ⋅  4

In [58]:
@show 2a

2a = [2 0; 0 8]


2×2 Diagonal{Int64, Vector{Int64}}:
 2  ⋅
 ⋅  8

In [59]:
b = rand(2, 2)

2×2 Matrix{Float64}:
 0.359826  0.970662
 0.457031  0.0440165

In [62]:
@show b * a

b * a = [0.3598260394447941 3.882648310716213; 0.4570308385315154 0.17606598656735883]


2×2 Matrix{Float64}:
 0.359826  3.88265
 0.457031  0.176066

In [68]:
b = [1.0 2.0; 3.0 4.0]
b - Diagonal([1.0, 1.0])

2×2 Matrix{Float64}:
 0.0  2.0
 3.0  3.0

In [72]:
b = [1.0 2.0; 3.0 4.0]
b - I ## I is an identity matrix

2×2 Matrix{Float64}:
 0.0  2.0
 3.0  3.0

In [74]:
typeof(I)

UniformScaling{Bool}

In [78]:
x = [1, 2, 3]
y = x ## name y is bound to whatever x is bound to 
z = [2, 3, 4]
y = z ## only changes the binding not the value
@show (x, y, z);

(x, y, z) = ([1, 2, 3], [2, 3, 4], [2, 3, 4])


In [79]:
x = [1, 2, 3]
y = x
z = [2, 3, 4]
y .= z ## like the reverse and you change what it got binded to
@show (x, y, z);

(x, y, z) = ([2, 3, 4], [2, 3, 4], [2, 3, 4])
